
all_medications = {
    'allergy' : ['BENADRYL Allergy ULTRATABS Tablets with Allergy Relief and Diphenhydramine HCI 25mg', 
                 'Epinephrine Auto-Injector Adult 0.3mg'],
    'cold cough congestion': ['Vicks DayQuil and Nyquil SEVERE Cold',
                              'Flu and Congestion Medicine and Congestion Medicine LiquiCaps Convenience Pack - Relieves Cough, Sore Throat, Congestion, Fever and Runny Nose, Daytime & Nighttime, 48 CT', 
                              'Vicks Vapo Steam Cough Suppressant', 
                              'Tylenol Child & Adult Oral Suspension, Pain & Fever, Cherry, 8 fl. Oz', 
                              'Navage Nasal Care Saline Nasal Irrigation Kit', 
                              'Sinex Severe Vicks Nasal Decongestant Spray, Twin Pack, 1 oz', 
                              'Ricola Nautral Herb Cough Drops', 
                              'Betadine Antiseptic Sore Throat Garagle, 8 OZ'], 
    'fever': ['Advil Liqui-Gels Pain Reliever and Fever Reducer, Solubilized Ibuprofen 200mg', 
              'Liquid Fast Pain Relief', 
              'Tylenol Extra Strength Rapid Release Gels with Acetaminophen'], 
    'migraine': ['Motrin IB Liquid Gels, Ibuprofen 200mg, Pain & Fever Relief Capsules', 
                 'BeKOOOL Migraine Temple Roll-On, 0.17 fl oz', 'Excedrin Migraine Caplets for Migraine Pain Relief'], 
    'bodyache': ['Icy Hot Pain Relieving Topical Analgesic Back Patch, 5 CT', 
                 'CVS Health Peas Hot or Cold Therapy Pack'], 
    'stomachache': ['Original Liquid, 5-Symptom Upset Stomach Fast Relief Original 8.0 fl oz'],
    'burn': ['CVS Health Sterile Hydrogel Burn Pads 4CT', 
             'Gold Bond Medicated Extra Strength Body Powder', 
             'CVS Health Bacitracin Ointment, 1 OZ'], 
    'itch': ['CeraVe Itch Relief Moisturizing Cream,  Steroid Free, 12 OZ', 
             'Aquaphor Advanced Therapy Healing Ointment Skin Protectant', 
             'Eucerin Eczema Relief Body Creme'], 
    'cut': ['Band-Aid Brand Adhesive Bandage Family Variety Pack, Assorted, 110 CT', 
            'Band-Aid Brand Water Block Flex Waterproof Adhesive Pads, Large, 6 CT'],
    'vitamins': ['Culturelle Digestive Health, Daily Probiotic Capsules', 
                 'Vitafusion Women\'s Bone and Metabolism Daily Multivitamin Gummy Formula, 150CT', 
                 'Vitafusion Men\'s Daily MultiVitamin Formula Gummy Vitamins'], 
    'supplements': ['Natures Bounty Fish Oil with Omega-3 Softgels 1200mg, 360CT ', 
                    'Nature\'s Bounty Odorless Fish Oil Softgels 2400mg, 90CT'], 
    'mood': ['Nature\'s Bounty Anxiety & Stress Relief, Ashwagandha KSM-66*, 50 CT', 
             'Natural Vitality Calm Magnesium Supplement Gummies, Raspberry-Lemon Flavor, 120 CT']
    }
